version: "3"

services:
    db:
#       strange init error with mariadb :(
#        image: mariadb 
        image: mysql/mysql-server
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        networks:
            - internal
        volumes:
            - db_data:/var/lib/mysql
            - ./init_db:/docker-entrypoint-initdb.d/
        env_file:
            - ./env/db.env
        secrets:
            - mysql-root-password

volumes:
    db_data:

networks:
    internal:

secrets:
  mysql-root-password:
    file: ./secrets/mysql-root-pw
