version: "3"

services:
    wp1:
        depends_on:
            - db
        image: wordpress:latest
        volumes:
            - wp1_data:/var/www/html
        restart: unless-stopped
#           secrets:
#               - wp1-mysql-password
        env_file:
            - ./env/db_host.env
            - ./env/wp.1.env
        networks:
            - internal

#secrets:
#    wp1-mysql-password:
#    file: ./secrets/wp1-mysql-pw

volumes:
    wp1_data:
