version: "3"

services:
    wp2:
        depends_on:
            - db
        image: wordpress:latest
        volumes:
            - wp2_data:/var/www/html
        restart: unless-stopped
#        secrets:
#            - wp2-mysql-password
        env_file:
            - ./env/db_host.env
            - ./env/wp.2.env
        networks:
            - internal

#secrets:
#    wp2-mysql-password:
#    file: ./secrets/wp2-mysql-pw

volumes:
    wp2_data:
