CREATE DATABASE wp1;
CREATE USER 'wp1'@'%';
GRANT ALL PRIVILEGES ON wp1.* TO 'wp1'@'%';

CREATE DATABASE wp2;
CREATE USER 'wp2'@'%';
GRANT ALL PRIVILEGES ON wp2.* TO 'wp2'@'%';

CREATE DATABASE proxy;
CREATE USER 'proxy'@'%';
GRANT ALL PRIVILEGES ON proxy.* TO 'proxy'@'%';
